services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n-instance
    ports:
      - "5678:5678"
    command: start --tunnel
    restart: unless-stopped
    stdin_open: true
    tty: true