services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n-instance
    ports:
      - "5678:5678"
    command: start --tunnel
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - smartpickr-net
  
  smartpickr-front:
    build:
      context: ..
      dockerfile: docker/Dockerfile.smartpickr
    container_name: smartpickr-front
    ports:
      - "8501:8501"
    depends_on:
      - n8n
    networks:
      - smartpickr-net
  
networks:
  smartpickr-net:
    driver: bridge