services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n-instance
    ports:
      - "5678:5678"
    command: start --tunnel
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      - N8N_DEFAULT_TIMEOUT=600000          # 10 minutes in milliseconds
      - EXECUTIONS_TIMEOUT=3600             # 1 hour in seconds  
      - EXECUTIONS_TIMEOUT_MAX=7200         # Max execution time in seconds
      - WEBHOOK_TIMEOUT=600000              # Webhook timeout in milliseconds
      - N8N_NODE_FUNCTION_TIMEOUT=600000    # Individual node timeout in milliseconds
    networks:
      - smartpickr-net
  
  smartpickr-front:
    build:
      context: ..
      dockerfile: docker/Dockerfile.smartpickr
    container_name: smartpickr-front
    ports:
      - "8501:8501"
    depends_on:
      - n8n
    networks:
      - smartpickr-net
  
networks:
  smartpickr-net:
    driver: bridge